export const mockData = {
  films: [
    {
      id: 1,
      filmName: `Some name`,
      posterImage: `Some url`,
      previewImage: `Some url`,
      backgroundImage: `http://sume.url`,
      backgroundColor: `#000000`,
      filmSrc: `Some url`,
      filmPreview: `Some url`,
      genre: `Some genre`,
      release: 1999,
      runtime: 99,
      rating: 99,
      scoresCount: 99,
      describe: `Some description`,
      director: `Director`,
      actors: [`Actor`, `Actor`],
      isFavorite: false,
    },
    {
      id: 2,
      filmName: `Some name`,
      posterImage: `Some url`,
      previewImage: `Some url`,
      backgroundImage: `http://sume.url`,
      backgroundColor: `#000000`,
      filmSrc: `Some url`,
      filmPreview: `Some url`,
      genre: `Some genre`,
      release: 1999,
      runtime: 99,
      rating: 99,
      scoresCount: 99,
      describe: `Some description`,
      director: `Director`,
      actors: [`Actor`, `Actor`],
      isFavorite: false,
    },
    {
      id: 3,
      filmName: `Some name`,
      posterImage: `Some url`,
      previewImage: `Some url`,
      backgroundImage: `http://sume.url`,
      backgroundColor: `#000000`,
      filmSrc: `Some url`,
      filmPreview: `Some url`,
      genre: `Some genre`,
      release: 1999,
      runtime: 99,
      rating: 99,
      scoresCount: 99,
      describe: `Some description`,
      director: `Director`,
      actors: [`Actor`, `Actor`],
      isFavorite: false,
    },
    {
      id: 4,
      filmName: `Some name`,
      posterImage: `Some url`,
      previewImage: `Some url`,
      backgroundImage: `http://sume.url`,
      backgroundColor: `#000000`,
      filmSrc: `Some url`,
      filmPreview: `Some url`,
      genre: `Some genre`,
      release: 1999,
      runtime: 99,
      rating: 99,
      scoresCount: 99,
      describe: `Some description`,
      director: `Director`,
      actors: [`Actor`, `Actor`],
      isFavorite: false,
    },
  ],
  promoFilmData: {
    id: 4,
    filmName: `Some name`,
    posterImage: `Some url`,
    previewImage: `Some url`,
    backgroundImage: `http://sume.url`,
    backgroundColor: `#000000`,
    filmSrc: `Some url`,
    filmPreview: `Some url`,
    genre: `Some genre`,
    release: 1999,
    runtime: 99,
    rating: 99,
    scoresCount: 99,
    describe: `Some description`,
    director: `Director`,
    actors: [`Actor`, `Actor`],
    isFavorite: false,
  },
  comments: [
    {
      id: 0,
      user: {
        id: 2,
        name: `Author name`,
      },
      rating: 9.9,
      comment: `Some comment`,
      date: `January 01, 2001`,
    },
    {
      id: 1,
      user: {
        id: 1,
        name: `Author name`,
      },
      rating: 9.9,
      comment: `Some comment`,
      date: `January 01, 2001`,
    }

  ],
  showedFilmsCount: 8,
  filmId: 2,
  selectedGenre: `All genres`,
};
